name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (cron runs in UTC)
  workflow_dispatch:         # lets you run it manually from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: keep-render-alive
      cancel-in-progress: true
    steps:
      - name: Ping Render app
        run: |
          set -e
          URL="https://kp-remodeling-api.onrender.com"
          echo "Pinging $URL..."
          # --fail makes non-2xx exit; --max-time prevents hangs
          curl --silent --show-error --fail --location --max-time 20 "$URL" > /dev/null
          echo "OK"
